apiVersion: v1
kind: Service
metadata:
  name: sample-servicev2
  labels:
    app: javasample
spec:
  ports:
  - port: 8081
    nodePort: 30201
    name: http
    targetPort: 8081
  type: NodePort
  selector:
    app: javasample