apiVersion: v1
kind: Service
metadata:
  name: sample-servicev2
  labels:
    app: javasample
spec:
  clusterIP: 172.18.167.83
  ports:
  - port: 8081
    nodePort: 80881
    name: http
    targetPort: 8081
  type: NodePort
  selector:
    app: javasample