apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app: javasample
spec:
  clusterIP: 106.12.158.23 
  ports:
  - port: 8081
    nodePort: 80881
    name: http
    targetPort: 8081
  type: NodePort
  selector:
    app: javasample