apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javasample
  namespace: demo
spec: 
  template: 
    metadata: 
      labels: 
        app: javasample
    spec: 
      containers: 
      - name: javasample
        image: registry.baidubce.com/service/javasample:1.0
        imagePullPolicy: IfNotPresent