apiVersion: apps/v1
kind: Deployment
metadata:
  name: javasample
  namespace: flux
spec:
  replicas: 1
  selector:
	matchLabels:
	  name: javasample
  strategy:
	type: Recreate
  template:
	metadata:
	  annotations:
		prometheus.io/port: "3031" 
	  labels:
		name: javasample
	spec:
	  nodeSelector:
		beta.kubernetes.io/os: linux
	  containers:
	  - name: javasample
		image: registry.baidubce.com/service/javasample:1.0
		imagePullPolicy: IfNotPresent     
		args:
		- --listen-metrics=:3031
