apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: javasamplev1
  namespace: demo
spec: 
  template: 
    metadata: 
      labels: 
        app: javasample 
    spec: 
      containers: 
      - name: javasample
        image: registry.baidubce.com/service/javasample:1.0
        imagePullPolicy: IfNotPresent